# Generated by Django 3.2.25 on 2024-04-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_mail', '0002_auto_20240418_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplemailconfig',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='LinkedIn Url'),
        ),
        migrations.AddField(
            model_name='simplemailconfig',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='TikTok Url'),
        ),
    ]
